name: Quantum Connectors
main: Ne0nx3r0.QuantumConnectors.QuantumConnectors
version: 0.4
authors:
  - Ne0nx3r0
  - Feildmaster
  - Niftymonkey
commands:
  qc:
    description: Quantum Connector Commands
permissions:
    QuantumConnectors.*:
      description: Allows all permissions
      children:
        QuantumConnectors.create : true
        QuantumConnectors.edit : true
        QuantumConnectors.break : true
    QuantumConnectors.create:
      description: Allows creation of circuits
      default: op
    QuantumConnectors.edit:
      description: Allows edit of circuits (Coming soon)
      default: op
    QuantumConnectors.break:
      description: Allows breaking of receivers/circuits
      default: op