name: Quantum Connectors
main: Ne0nx3r0.QuantumConnectors.QuantumConnectors
version: 0.4
authors:
  - Ne0nx3r0
  - Feildmaster
  - Niftymonkey
commands:
  qc:
    description: Quantum Connector Commands